on: [push]

jobs:
  weblog_import:
    runs-on: debian-latest
    name: weblog.lol importer
    steps:
      - uses: actions/checkout@v3
      - id: weblog_import
        uses: newbold/gh_actions_test@v11
        env:
          ADDRESS: adam
          WEBLOG_API_KEY: ${{ secrets.WEBLOG_API_KEY }}
